### ISSUE TITLE
CSS Conflicts with bootstrap

### ISSUE THREAD

**Issue by Rokani** [Morasiu/BlazorTimeline#5]
Hi, I found an issues while I was using your module.
To summarize your TimelineItem.razor.css overrides bootstrap's css witch occurs a change of the button aspect with the class name "btn" (they turn into purple the same color than the button we can use on the TimelineItem).

**Comment by Morasiu** [comment]
Oh... I can change the class name to "timeline-button". Would this solve that issue?

**Comment by Rokani** [comment]
Yeah I think it would work if it didn't annoy you too much then I will give you a feedback

**Comment by Morasiu** [comment]
Fixed in version `1.2.1`

**Comment by Rokani** [comment]
It works! Thanks a lot !

By the way your module is awesome 👍
