### ISSUE TITLE
Timeline style not working with MudBlazor

### ISSUE THREAD

**Issue by koffisani** [Morasiu/BlazorTimeline#8]
I find your package very interesting but getting stuck to have styles applied to my Items.

I can find that, styles not applying and also, the position not working.

```csharp
<Timeline
    Title="Historique"
    TitleBgColor="#554DE0"
    TitleColor="#FFFFFF"
    TextColor="#F3F3F3"
    TextBgColor="#212121"
    ItemPositionOption="@ItemPositionOption.Manual">

    @if (_isLoaded)
    {
        @if (_timelineItems.Count() >= 0)
        {
            @foreach (var item in _timelineItems)
            {
                <TimelineItem Title="Entrée" Time="@item.DateEvenement.ToString("D")"
                              Position="@(_timelineItems.IndexOf(item) % 2 == 0 ? ItemPosition.Left : ItemPosition.Right)">

                    <p>@item.details</p>
                </TimelineItem>
            }
        }
    }
</Timeline>
```

What have I done wrong ?

**Comment by Morasiu** [comment]
I will check that and let you know

**Comment by Morasiu** [comment]
Just tested in on MudBlazor You can check this on branch  `mudblazor-test`. It works fine

Can you provide me a MudBlazor version that you are using?

**Comment by koffisani** [comment]
Thank you, @Morasiu, for your reply. I'm using Mudblazor 5.0.14 for .NET 5 Core.

Thank you.

**Comment by koffisani** [comment]
Also, inspecting the generated html, I found this : 

![image](https://user-images.githubusercontent.com/8408477/150753287-ff416525-888a-4a10-880d-9c01b7365183.png)

Is it the expected output ?

**Comment by Morasiu** [comment]
I am testing it on the same version (MudBlazor 5.x) and it works. Can you provide me with your code sample in which you have some MudBlazor and BlazorTimeline together? 

Yeah. I think it should look like this
